### ISSUE TITLE
4bit version not working?

### ISSUE THREAD

**Issue by imadcap** [camenduru/falcon-40b-instruct-lambda#3]
Hello

I noticed that load_in_4bit was commented. On my side, I did not get it to work. The 40b model fits into 4 GPUs (16Go each) but then at the inference time the error "at::cuda::blas::gemm: not implemented for N3c108BFloat16E" occurs.

https://github.com/camenduru/falcon-40b-instruct-lambda/blob/d86bbdb687b3755aea20d205a09bf7d6ba5e9f85/run.py#LL15C6-L15C18

Do you happen to know why?thank yo!

**Comment by camenduru** [comment]
thanks for the info ❤
