### ISSUE TITLE
cuda out of memory issue on a single A100-80GB

### ISSUE THREAD

**Issue by HongyunQiu** [camenduru/falcon-40b-instruct-lambda#4]
Hello. I can run the ipynb very well but if the output context is a little more, it always meet something like this: "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.19 GiB total capacity; 78.10 GiB already allocated; 8.56 MiB free; 78.23 GiB reserved" It Seems the GPU requirement is just a little more for  80GB VRAM.  This problem prevents it from outputting a longer context.

**Comment by camenduru** [comment]
thanks for the info ❤
